### ISSUE TITLE
Compatibility with Rockpi4

### ISSUE THREAD

**Issue by SaimShuja** [pftf/RPi4#126]
Can this firmware be used on Rockpi4? It has arm64 processor RK3399.
https://wiki.radxa.com/Rockpi4/hardware

**Comment by pbatard** [comment]
No. The Raspberry Pi 4 uses a completely different SoC (A Broadcom 2711).

It'd be a bit like asking _"Can I use the new macOS for M1 processors on an x86 PC?"_. It's just not compatible at all.

There has been some effort to try to produce a UEFI firmware for RK3399 platforms (See https://github.com/andreiw/rk3399-edk2), but, because this is a costly effort in terms of development, especially when it relies entirely on volunteers, this effort is pretty much stalled right now.

**Comment by SaimShuja** [comment]
Thankyou
