### ISSUE TITLE
Raspberry Pi 4 UEFI won't boot

### ISSUE THREAD

**Issue by ChibiANUBIS** [pftf/RPi4#178]
Hello my dear, I reinstall Windows 10 on UEFI in my SD Card, I use the WoR tool,
But my monitor display "No signal" and my Raspberry yellow LED display 4 times,

Can you help please,

Regards.

**Comment by sunnywang-arm** [comment]
@ChibiANUBIS 
I would suggest that you just simply unzip the RPi4_UEFI_Firmware_v1.27.zip in https://github.com/pftf/RPi4/releases/tag/v1.27 to the SD card's partition. There are some issues with v1.28, and later, so v1.27 may be a better choice for you at this moment. 
By the way, the partition should be formatted in FAT32. If it works, it may be something wrong with the partitions and files generated by the WoR tool rather than the UEFI firmware itself. For WoR related issues, it would be better to go to the community or bug system: 
https://www.worproject.ml/community
https://www.worproject.ml/bugtracker/my_view_page.php

**Comment by ChibiANUBIS** [comment]
Thanks my dear for your help, but is the same, Is not possible for me to run anything

**Comment by sunnywang-arm** [comment]
@ChibiANUBIS 
Could you connect the serial console to get the serial log?

**Comment by ChibiANUBIS** [comment]
> @ChibiANUBIS
> Could you connect the serial console to get the serial log?

No, what is this ?

**Comment by sunnywang-arm** [comment]
@ChibiANUBIS 
Here you go.
https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable/overview

**Comment by ChibiANUBIS** [comment]
> @ChibiANUBIS
> Here you go.
> https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable/overview

Is not possible to enable with the WoR...

**Comment by sunnywang-arm** [comment]
> > @ChibiANUBIS
> > Here you go.
> > https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable/overview
> 
> Is not possible to enable with the WoR...

@ChibiANUBIS 
Hmm... I don't understand. 
Even if you use WoR to produce the UEFI boot partition and UEFI firmware, you should still be able to enable the serial console by using the steps mentioned in the link and a USB To TTL cable. We just want to get serial console output from firmware rather than OS.
- https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable/you-will-need
- https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable/connect-the-lead
- https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable/test-and-configure
