### ISSUE TITLE
Booting firmware over the network via PXE

### ISSUE THREAD

**Issue by samip5** [pftf/RPi4#184]
How would one boot this firmware from PXE using Pi's network booting functionality or is it not possible?

**Comment by e3palma** [comment]
I accomplished this by using this guide from  [hackaday](https://hackaday.io/project/179793-ucm4/log/196275-netbooting-compute-module-4-in-ucm4-carrierl)

**Comment by jlinton** [comment]
I think others have accomplished it too, the trick along the way is booting the firmware image you get here natively on a SD card, changing the UEFI settings (lifting the 3G limit, etc) for your environment, saving the settings. Those settings are saved to the UEFI image itself. Then copying that image with the saved settings to the tftp server rather than the ones we provide here so that the pi's come up with whatever settings your interested in.
