### ISSUE TITLE
How to modify boot screen？

### ISSUE THREAD

**Issue by yyds-yyds-yyds** [pftf/RPi4#211]
Hello, I want to ask a question, how to modify the boot screen? I want to change the boot screen, but I don't know how to change it. Can you tell me how to change it?

**Comment by hellosway** [comment]
What exactly do you mean by boot screen. Is it the raspberry pi logo with the progress bar at the bottom.

**Comment by yyds-yyds-yyds** [comment]
Yes, it's the logo. How to change it! Sorry, my English is poor and difficult to describe clearly. Thank you for reading patiently.

**Comment by TheMindVirus** [comment]
https://github.com/tianocore/edk2-non-osi/blob/master/Platform/RaspberryPi/Drivers/LogoDxe/Logo.bmp

**Comment by yyds-yyds-yyds** [comment]
So the boot image cannot be changed?

**Comment by TheMindVirus** [comment]
It can be changed but UEFI in its current state needs recompiling after you change it in the repository. I have changed mine in this way.

In the RPI_EFI.fd archive itself it seems to have been turned into a binary stream which is mangled with other data inside LogoDxe.efi instead of being an editable .bmp file.

**Comment by pbatard** [comment]
Changing the boot logo requires editing https://github.com/tianocore/edk2-non-osi/blob/master/Platform/RaspberryPi/Drivers/LogoDxe/Logo.bmp as @TheMindVirus pointed out and recompiling your own UEFI Firmware. We do not support trying to edit the logo in the `RPI_EFI.fd` that is provided from this repository.
