### ISSUE TITLE
Stuck on raspberry pi logo

### ISSUE THREAD

**Issue by ArshithsTechVlog** [pftf/RPi4#223]
I can't see the windows spinning dots but I reinstalled it 5 times but it still does not work PLEASE HELP ME because I am trying it for 3 days

**Comment by Marcinoo97** [comment]
wow. You have provided enough information for anyone to be able to help you. Good luck.

**Comment by pbatard** [comment]
if you see the Windows spinning dots, it means that the UEFI Firmware has properly handed over boot to Windows, therefore you have a Windows boot issue rather than a UEFI boot issue. This issue tracker is only for UEFI boot issues.

You should ask about your issue in user websites or forums that are dealing with the installation of Windows on Raspberry Pi.
