### ISSUE TITLE
Legacy boot still possible?

### ISSUE THREAD

**Issue by nandlab** [pftf/RPi4#239]
I have a question regarding the RPi4 UEFI firmware.
After flashing the RPi4 UEFI firmware, will booting legacy (non-UEFI) distros still be possible? Or will it only support UEFI distros?

**Comment by pbatard** [comment]
"legacy" is usually a term that's reserved for x86 based PC (since it basically means "x86 BIOS boot", and there is no such thing as BIOS on an ARM platforms).

But I guess your question is: _"Can you still use the proprietary default Raspberry Pi bootloaders to boot a _non-UEFI_ Linux distro that was customized to work with the proprietary Raspberry Pi bootloaders?"_ and the answer to that is yes, since the UEFI firmware does not replace anything, so whatever worked before you used the UEFI firmware will still work even after you use UEFI.
