### ISSUE TITLE
If you can, add bois time, can't even, don't force

### ISSUE THREAD

**Issue by bzy-080408** [pftf/RPi4#53]
If you can, add bois time, can't even, don't force

**Comment by pbatard** [comment]
Please clarify what you mean, as we have no idea what you request and will have no choice but to close this issue otherwise.

Also please understand that, as indicated in the very prominent README notice, this firmware is not finalized and still missing features. And also understand that, in case this is what you are asking, the Rasbperry Pi has no native Real-Time-Clock, so it cannot keep time on its own.

**Comment by bzy-080408** [comment]
OK，I see
